name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  build: #use Intel SDK environment to test compilation

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sgx-emm
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Checkout linux-sgx
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      with:
        repository: intel/linux-sgx.git
        ref: 'main'
        path: ./linux-sgx
    - name: Setup tlibc
      run: ln -s ./linux-sgx/common/inc/tlibc/ tlibc_stub
    - name: Compilation test
      run: make -f Makefile_test
